### ISSUE TITLE
How many bottles now?

### ISSUE THREAD

**Issue by munterkalmsteiner** [mickesv/BigDataAnalytics#8]
This is about solving the ramping problem described [here](https://github.com/mickesv/BigDataAnalytics/blob/main/Documentation/Big-Data-Analytics.org#expand-with-aleph-null-bottles-of-beer).

So, I *tried* to crawl through the code and get an approximation of a mental map of what is going on in the code. I *think* I get the FP (`elegant`) expander but you lost me with the `beer`. I understand the ramping problem, but how is that actually solved? I can see that `beer` moved the overlap detection from clojure space to a mongo query (`get-overlapping-candidates', now **that** query is easy to read; not) and the clones are stored in the database instead of in memory. But is that the actual *core* of the solution, or where is it?

**Comment by mickesv** [comment]
There are a number of factors that help us out here. First is that only one candidate (and possible expansions) is kept in memory. Second is that we shift processing from clojure to the database, so the database connection does not time out as easily.

But the biggest factor is, I think, that the bundle of joy `get-overlapping-candidates` is a series of _filters_ (which databases are really good at) where already the first `$match` quickly reduces the number of elements to continue looking at.

Also, for every successfully expanded clone the set of candidates shrinks, whereas in the "elegant" solution we just get more and more clones to match every new candidate with. If the database can execute the query the first time (and why shouldn't it, it is just a set of filters), life is only going to get easier.
